app_path:
  amazing_midi: C:\Program Files (x86)\AmazingMIDI\amazingmidi.exe
  anthemscore: C:\Program Files (x86)\AnthemScore\AnthemScore.exe
  audiveris: C:\Users\daval\audiveris
  muse_score: C:\Program Files\MuseScore 3\bin\MuseScore3.exe
  open_close_source: close_source
color:
  black: 0,20,0
  right: 0,0,20
  upcoming: 20,20,20
  white: 0,0,20
  wrong: 20,0,0
lighting scheme:
  beginner: BW
  expert: BW
  intermediate: UI
options:
  normalize ppqn: true
  right/wrong notification: true
  timing notification: true
port:
  arduino: COM3
  piano: CASIO USB-MIDI 1
  piano_size: '76'
